export interface WordEntry {
  word: string;
  isNonsense: boolean;
  level: string;
  levelNumber: number;
  coinValue: number;
  phonicFamily: string;
  phonicPattern: string;
}

export const LEVEL3_WORDS: WordEntry[] = [
  // 3A – vowel teams oi, oy, igh
  { word: "oil", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "coil", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "foil", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "soil", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "toil", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "coin", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "join", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "point", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "joint", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "boy", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "joy", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "toy", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "ploy", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "annoy", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "enjoy", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "high", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "sigh", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "night", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "light", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "right", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "fight", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "tight", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "bright", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "flight", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "slight", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  // 3A nonsense
  { word: "voil", isNonsense: true, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "zoy", isNonsense: true, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "digh", isNonsense: true, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "boit", isNonsense: true, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "wight", isNonsense: true, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "foy", isNonsense: true, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  // 3A additional words
  { word: "broil", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "groin", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "hoist", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "loin", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "moist", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "noise", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "void", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "ahoy", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "alloy", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "cloy", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "convoy", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "coy", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "decoy", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "deploy", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "destroy", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "employ", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "envoy", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "loyal", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "blight", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "delight", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "fright", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "might", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "plight", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "sight", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "thigh", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "midnight", isNonsense: false, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },
  { word: "zoil", isNonsense: true, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oi", phonicPattern: "vowel-team-oi" },
  { word: "bloy", isNonsense: true, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "oy", phonicPattern: "vowel-team-oy" },
  { word: "figh", isNonsense: true, level: "3A", levelNumber: 3, coinValue: 12, phonicFamily: "igh", phonicPattern: "vowel-team-igh" },

  // 3B – ie (pie/piece), ph, ea (short/bread), au, aw
  { word: "pie", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ie", phonicPattern: "vowel-team-ie" },
  { word: "tie", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ie", phonicPattern: "vowel-team-ie" },
  { word: "lie", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ie", phonicPattern: "vowel-team-ie" },
  { word: "die", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ie", phonicPattern: "vowel-team-ie" },
  { word: "piece", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ie", phonicPattern: "vowel-team-ie" },
  { word: "field", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ie", phonicPattern: "vowel-team-ie" },
  { word: "phone", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ph", phonicPattern: "ph" },
  { word: "photo", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ph", phonicPattern: "ph" },
  { word: "graph", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ph", phonicPattern: "ph" },
  { word: "phrase", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ph", phonicPattern: "ph" },
  { word: "dolphin", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ph", phonicPattern: "ph" },
  { word: "bread", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ea-short", phonicPattern: "ea-short" },
  { word: "dead", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ea-short", phonicPattern: "ea-short" },
  { word: "head", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ea-short", phonicPattern: "ea-short" },
  { word: "spread", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ea-short", phonicPattern: "ea-short" },
  { word: "thread", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ea-short", phonicPattern: "ea-short" },
  { word: "cause", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "fault", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "haul", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "launch", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "paw", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "jaw", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "claw", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "draw", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "straw", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  // 3B nonsense
  { word: "vie", isNonsense: true, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ie", phonicPattern: "vowel-team-ie" },
  { word: "phom", isNonsense: true, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ph", phonicPattern: "ph" },
  { word: "dread", isNonsense: true, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ea-short", phonicPattern: "ea-short" },
  { word: "zaw", isNonsense: true, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "faud", isNonsense: true, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  // 3B additional words
  { word: "brief", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ie", phonicPattern: "vowel-team-ie" },
  { word: "chief", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ie", phonicPattern: "vowel-team-ie" },
  { word: "grief", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ie", phonicPattern: "vowel-team-ie" },
  { word: "niece", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ie", phonicPattern: "vowel-team-ie" },
  { word: "shield", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ie", phonicPattern: "vowel-team-ie" },
  { word: "thief", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ie", phonicPattern: "vowel-team-ie" },
  { word: "yield", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ie", phonicPattern: "vowel-team-ie" },
  { word: "alphabet", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ph", phonicPattern: "ph" },
  { word: "paragraph", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ph", phonicPattern: "ph" },
  { word: "trophy", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ph", phonicPattern: "ph" },
  { word: "elephant", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ph", phonicPattern: "ph" },
  { word: "breakfast", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ea-short", phonicPattern: "ea-short" },
  { word: "feather", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ea-short", phonicPattern: "ea-short" },
  { word: "health", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ea-short", phonicPattern: "ea-short" },
  { word: "heaven", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ea-short", phonicPattern: "ea-short" },
  { word: "heavy", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ea-short", phonicPattern: "ea-short" },
  { word: "leather", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ea-short", phonicPattern: "ea-short" },
  { word: "ready", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ea-short", phonicPattern: "ea-short" },
  { word: "steady", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ea-short", phonicPattern: "ea-short" },
  { word: "sweat", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ea-short", phonicPattern: "ea-short" },
  { word: "weather", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ea-short", phonicPattern: "ea-short" },
  { word: "author", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "autumn", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "sauce", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "awful", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "crawl", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "flaw", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "hawk", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "raw", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "thaw", isNonsense: false, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "phig", isNonsense: true, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ph", phonicPattern: "ph" },
  { word: "zawl", isNonsense: true, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "au-aw", phonicPattern: "au-aw" },
  { word: "veath", isNonsense: true, level: "3B", levelNumber: 3, coinValue: 12, phonicFamily: "ea-short", phonicPattern: "ea-short" },

  // 3C – -tion, -sion endings
  { word: "action", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "station", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "nation", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "motion", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "lotion", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "potion", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "mention", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "question", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "fraction", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "fiction", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "section", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "direction", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "vision", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "mission", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "passion", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "tension", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "mansion", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "extension", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  // 3C nonsense
  { word: "vaction", isNonsense: true, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "zosion", isNonsense: true, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "fention", isNonsense: true, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "blession", isNonsense: true, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  // 3C additional words
  { word: "addition", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "attention", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "collection", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "condition", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "construction", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "donation", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "emotion", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "imagination", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "invitation", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "location", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "operation", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "option", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "population", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "position", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "production", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "reaction", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "rotation", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "suggestion", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "vacation", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "solution", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "conclusion", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "confusion", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "decision", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "discussion", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "division", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "expression", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "impression", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "invasion", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "permission", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "possession", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "revision", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "session", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "version", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "suspension", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "explosion", isNonsense: false, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "vestion", isNonsense: true, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },
  { word: "bansion", isNonsense: true, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-sion", phonicPattern: "suffix-sion" },
  { word: "pention", isNonsense: true, level: "3C", levelNumber: 3, coinValue: 12, phonicFamily: "-tion", phonicPattern: "suffix-tion" },

  // 3D – soft c/g, schwa, doubling rule, suffixes
  { word: "cell", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-c", phonicPattern: "soft-c" },
  { word: "cent", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-c", phonicPattern: "soft-c" },
  { word: "city", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-c", phonicPattern: "soft-c" },
  { word: "cycle", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-c", phonicPattern: "soft-c" },
  { word: "place", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-c", phonicPattern: "soft-c" },
  { word: "race", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-c", phonicPattern: "soft-c" },
  { word: "space", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-c", phonicPattern: "soft-c" },
  { word: "gem", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-g", phonicPattern: "soft-g" },
  { word: "gel", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-g", phonicPattern: "soft-g" },
  { word: "germ", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-g", phonicPattern: "soft-g" },
  { word: "giant", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-g", phonicPattern: "soft-g" },
  { word: "giraffe", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-g", phonicPattern: "soft-g" },
  { word: "age", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-g", phonicPattern: "soft-g" },
  { word: "cage", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-g", phonicPattern: "soft-g" },
  { word: "page", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-g", phonicPattern: "soft-g" },
  { word: "stage", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-g", phonicPattern: "soft-g" },
  { word: "about", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "schwa", phonicPattern: "schwa" },
  { word: "above", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "schwa", phonicPattern: "schwa" },
  { word: "ago", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "schwa", phonicPattern: "schwa" },
  { word: "animal", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "schwa", phonicPattern: "schwa" },
  { word: "running", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "doubling-rule", phonicPattern: "doubling-rule" },
  { word: "sitting", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "doubling-rule", phonicPattern: "doubling-rule" },
  { word: "hopped", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "doubling-rule", phonicPattern: "doubling-rule" },
  { word: "bigger", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "doubling-rule", phonicPattern: "doubling-rule" },
  { word: "hottest", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "doubling-rule", phonicPattern: "doubling-rule" },
  // 3D nonsense
  { word: "vace", isNonsense: true, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-c", phonicPattern: "soft-c" },
  { word: "zell", isNonsense: true, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-c", phonicPattern: "soft-c" },
  { word: "fage", isNonsense: true, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-g", phonicPattern: "soft-g" },
  { word: "drumming", isNonsense: true, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "doubling-rule", phonicPattern: "doubling-rule" },
  { word: "bipping", isNonsense: true, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "doubling-rule", phonicPattern: "doubling-rule" },
  // 3D additional words
  { word: "ice", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-c", phonicPattern: "soft-c" },
  { word: "price", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-c", phonicPattern: "soft-c" },
  { word: "twice", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-c", phonicPattern: "soft-c" },
  { word: "rice", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-c", phonicPattern: "soft-c" },
  { word: "notice", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-c", phonicPattern: "soft-c" },
  { word: "grace", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-c", phonicPattern: "soft-c" },
  { word: "change", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-g", phonicPattern: "soft-g" },
  { word: "range", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-g", phonicPattern: "soft-g" },
  { word: "large", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-g", phonicPattern: "soft-g" },
  { word: "surge", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-g", phonicPattern: "soft-g" },
  { word: "plunge", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-g", phonicPattern: "soft-g" },
  { word: "awake", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "schwa", phonicPattern: "schwa" },
  { word: "alone", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "schwa", phonicPattern: "schwa" },
  { word: "among", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "schwa", phonicPattern: "schwa" },
  { word: "along", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "schwa", phonicPattern: "schwa" },
  { word: "batting", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "doubling-rule", phonicPattern: "doubling-rule" },
  { word: "cutting", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "doubling-rule", phonicPattern: "doubling-rule" },
  { word: "getting", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "doubling-rule", phonicPattern: "doubling-rule" },
  { word: "napping", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "doubling-rule", phonicPattern: "doubling-rule" },
  { word: "slipping", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "doubling-rule", phonicPattern: "doubling-rule" },
  { word: "lucky", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "suffix-rule", phonicPattern: "doubling-rule" },
  { word: "kindly", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "suffix-rule", phonicPattern: "doubling-rule" },
  { word: "peaceful", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "suffix-rule", phonicPattern: "doubling-rule" },
  { word: "thankful", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "suffix-rule", phonicPattern: "doubling-rule" },
  { word: "cheerful", isNonsense: false, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "suffix-rule", phonicPattern: "doubling-rule" },
  { word: "fice", isNonsense: true, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-c", phonicPattern: "soft-c" },
  { word: "zange", isNonsense: true, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-g", phonicPattern: "soft-g" },
  { word: "glurge", isNonsense: true, level: "3D", levelNumber: 3, coinValue: 12, phonicFamily: "soft-g", phonicPattern: "soft-g" },
];
