export interface WordEntry {
  word: string;
  isNonsense: boolean;
  level: string;
  levelNumber: number;
  coinValue: number;
  phonicFamily: string;
  phonicPattern: string;
}

export const LEVEL5_WORDS: WordEntry[] = [
  // 5A – silent letters: kn-, wr-, gn-, -mb, silent-l, silent-t
  { word: "knit", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "kn", phonicPattern: "silent-kn" },
  { word: "knot", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "kn", phonicPattern: "silent-kn" },
  { word: "know", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "kn", phonicPattern: "silent-kn" },
  { word: "knew", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "kn", phonicPattern: "silent-kn" },
  { word: "knee", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "kn", phonicPattern: "silent-kn" },
  { word: "knock", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "kn", phonicPattern: "silent-kn" },
  { word: "knight", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "kn", phonicPattern: "silent-kn" },
  { word: "wrap", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "wr", phonicPattern: "silent-wr" },
  { word: "wren", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "wr", phonicPattern: "silent-wr" },
  { word: "write", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "wr", phonicPattern: "silent-wr" },
  { word: "wrong", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "wr", phonicPattern: "silent-wr" },
  { word: "wrist", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "wr", phonicPattern: "silent-wr" },
  { word: "wreck", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "wr", phonicPattern: "silent-wr" },
  { word: "gnat", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "gn", phonicPattern: "silent-wr" },
  { word: "gnaw", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "gn", phonicPattern: "silent-wr" },
  { word: "gnome", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "gn", phonicPattern: "silent-wr" },
  { word: "lamb", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "-mb", phonicPattern: "silent-mb" },
  { word: "bomb", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "-mb", phonicPattern: "silent-mb" },
  { word: "climb", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "-mb", phonicPattern: "silent-mb" },
  { word: "comb", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "-mb", phonicPattern: "silent-mb" },
  { word: "dumb", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "-mb", phonicPattern: "silent-mb" },
  { word: "limb", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "-mb", phonicPattern: "silent-mb" },
  { word: "numb", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "-mb", phonicPattern: "silent-mb" },
  { word: "thumb", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "-mb", phonicPattern: "silent-mb" },
  { word: "calm", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-l", phonicPattern: "silent-l" },
  { word: "palm", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-l", phonicPattern: "silent-l" },
  { word: "half", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-l", phonicPattern: "silent-l" },
  { word: "calf", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-l", phonicPattern: "silent-l" },
  { word: "walk", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-l", phonicPattern: "silent-l" },
  { word: "talk", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-l", phonicPattern: "silent-l" },
  { word: "castle", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-t", phonicPattern: "silent-l" },
  { word: "whistle", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-t", phonicPattern: "silent-l" },
  { word: "listen", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-t", phonicPattern: "silent-l" },
  { word: "fasten", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-t", phonicPattern: "silent-l" },
  // 5A kn additions
  { word: "knack", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "kn", phonicPattern: "silent-kn" },
  { word: "knave", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "kn", phonicPattern: "silent-kn" },
  { word: "knead", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "kn", phonicPattern: "silent-kn" },
  { word: "kneel", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "kn", phonicPattern: "silent-kn" },
  { word: "knife", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "kn", phonicPattern: "silent-kn" },
  { word: "knob", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "kn", phonicPattern: "silent-kn" },
  // 5A wr additions
  { word: "wrath", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "wr", phonicPattern: "silent-wr" },
  { word: "wrench", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "wr", phonicPattern: "silent-wr" },
  { word: "wring", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "wr", phonicPattern: "silent-wr" },
  { word: "wrestle", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "wr", phonicPattern: "silent-wr" },
  // 5A gn additions
  { word: "gnash", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "gn", phonicPattern: "silent-wr" },
  { word: "gnarl", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "gn", phonicPattern: "silent-wr" },
  // 5A -mb additions
  { word: "crumb", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "-mb", phonicPattern: "silent-mb" },
  { word: "plumb", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "-mb", phonicPattern: "silent-mb" },
  { word: "tomb", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "-mb", phonicPattern: "silent-mb" },
  { word: "womb", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "-mb", phonicPattern: "silent-mb" },
  // 5A silent-l additions
  { word: "balk", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-l", phonicPattern: "silent-l" },
  { word: "chalk", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-l", phonicPattern: "silent-l" },
  { word: "folk", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-l", phonicPattern: "silent-l" },
  { word: "stalk", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-l", phonicPattern: "silent-l" },
  { word: "yolk", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-l", phonicPattern: "silent-l" },
  // 5A silent-t additions
  { word: "bristle", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-t", phonicPattern: "silent-l" },
  { word: "bustle", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-t", phonicPattern: "silent-l" },
  { word: "glisten", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-t", phonicPattern: "silent-l" },
  { word: "hustle", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-t", phonicPattern: "silent-l" },
  { word: "nestle", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-t", phonicPattern: "silent-l" },
  { word: "soften", isNonsense: false, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-t", phonicPattern: "silent-l" },
  // 5A nonsense
  { word: "knub", isNonsense: true, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "kn", phonicPattern: "silent-kn" },
  { word: "wrob", isNonsense: true, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "wr", phonicPattern: "silent-wr" },
  { word: "dumb", isNonsense: true, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "-mb", phonicPattern: "silent-mb" },
  { word: "zalm", isNonsense: true, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "silent-l", phonicPattern: "silent-l" },
  { word: "wristle", isNonsense: true, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "wr", phonicPattern: "silent-wr" },
  { word: "knuff", isNonsense: true, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "kn", phonicPattern: "silent-kn" },
  { word: "wreld", isNonsense: true, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "wr", phonicPattern: "silent-wr" },
  { word: "palb", isNonsense: true, level: "5A", levelNumber: 5, coinValue: 25, phonicFamily: "-mb", phonicPattern: "silent-mb" },

  // 5B – ch/k/ (Greek), que/k/, gue/g/, y-as-/i/, advanced schwa
  { word: "school", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  { word: "chord", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  { word: "chorus", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  { word: "chrome", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  { word: "anchor", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  { word: "stomach", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  { word: "unique", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "que", phonicPattern: "greek-que" },
  { word: "antique", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "que", phonicPattern: "greek-que" },
  { word: "technique", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "que", phonicPattern: "greek-que" },
  { word: "boutique", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "que", phonicPattern: "greek-que" },
  { word: "league", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "gue", phonicPattern: "greek-gue" },
  { word: "tongue", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "gue", phonicPattern: "greek-gue" },
  { word: "vague", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "gue", phonicPattern: "greek-gue" },
  { word: "rogue", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "gue", phonicPattern: "greek-gue" },
  { word: "gym", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "y-closed", phonicPattern: "y-closed" },
  { word: "myth", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "y-closed", phonicPattern: "y-closed" },
  { word: "crypt", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "y-closed", phonicPattern: "y-closed" },
  { word: "hymn", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "y-closed", phonicPattern: "y-closed" },
  { word: "syrup", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "y-closed", phonicPattern: "y-closed" },
  { word: "crystal", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "y-closed", phonicPattern: "y-closed" },
  { word: "banana", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "schwa-adv", phonicPattern: "y-closed" },
  { word: "camera", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "schwa-adv", phonicPattern: "y-closed" },
  { word: "calendar", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "schwa-adv", phonicPattern: "y-closed" },
  { word: "cabinet", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "schwa-adv", phonicPattern: "y-closed" },
  { word: "general", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "schwa-adv", phonicPattern: "y-closed" },
  // 5B greek-ch additions
  { word: "chaos", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  { word: "character", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  { word: "chemical", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  { word: "echo", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  { word: "mechanic", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  { word: "monarch", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  { word: "scheme", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  { word: "scholar", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  { word: "chronic", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  { word: "technical", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  // 5B que additions
  { word: "clique", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "que", phonicPattern: "greek-que" },
  { word: "critique", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "que", phonicPattern: "greek-que" },
  { word: "mystique", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "que", phonicPattern: "greek-que" },
  { word: "opaque", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "que", phonicPattern: "greek-que" },
  // 5B gue additions
  { word: "catalogue", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "gue", phonicPattern: "greek-gue" },
  { word: "colleague", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "gue", phonicPattern: "greek-gue" },
  { word: "dialogue", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "gue", phonicPattern: "greek-gue" },
  { word: "epilogue", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "gue", phonicPattern: "greek-gue" },
  { word: "fatigue", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "gue", phonicPattern: "greek-gue" },
  { word: "intrigue", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "gue", phonicPattern: "greek-gue" },
  { word: "prologue", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "gue", phonicPattern: "greek-gue" },
  // 5B y-closed additions
  { word: "cycle", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "y-closed", phonicPattern: "y-closed" },
  { word: "mystery", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "y-closed", phonicPattern: "y-closed" },
  { word: "nymph", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "y-closed", phonicPattern: "y-closed" },
  { word: "oxygen", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "y-closed", phonicPattern: "y-closed" },
  { word: "physics", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "y-closed", phonicPattern: "y-closed" },
  { word: "rhythm", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "y-closed", phonicPattern: "y-closed" },
  { word: "symbol", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "y-closed", phonicPattern: "y-closed" },
  { word: "syllable", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "y-closed", phonicPattern: "y-closed" },
  { word: "system", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "y-closed", phonicPattern: "y-closed" },
  // 5B schwa-adv additions
  { word: "animal", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "schwa-adv", phonicPattern: "y-closed" },
  { word: "another", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "schwa-adv", phonicPattern: "y-closed" },
  { word: "capital", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "schwa-adv", phonicPattern: "y-closed" },
  { word: "couple", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "schwa-adv", phonicPattern: "y-closed" },
  { word: "final", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "schwa-adv", phonicPattern: "y-closed" },
  { word: "loyal", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "schwa-adv", phonicPattern: "y-closed" },
  { word: "medal", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "schwa-adv", phonicPattern: "y-closed" },
  { word: "model", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "schwa-adv", phonicPattern: "y-closed" },
  { word: "parent", isNonsense: false, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "schwa-adv", phonicPattern: "y-closed" },
  // 5B nonsense
  { word: "chrot", isNonsense: true, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  { word: "clique", isNonsense: true, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "que", phonicPattern: "greek-que" },
  { word: "drogue", isNonsense: true, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "gue", phonicPattern: "greek-gue" },
  { word: "zym", isNonsense: true, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "y-closed", phonicPattern: "y-closed" },
  { word: "chrold", isNonsense: true, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  { word: "chrug", isNonsense: true, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "greek-ch", phonicPattern: "greek-ch" },
  { word: "zeym", isNonsense: true, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "y-closed", phonicPattern: "y-closed" },
  { word: "blogue", isNonsense: true, level: "5B", levelNumber: 5, coinValue: 25, phonicFamily: "gue", phonicPattern: "greek-gue" },
];
