export interface WordEntry {
  word: string;
  isNonsense: boolean;
  level: string;
  levelNumber: number;
  coinValue: number;
  phonicFamily: string;
  phonicPattern: string;
}

export const LEVEL4_WORDS: WordEntry[] = [
  // 4A – consonant-le syllable, dge
  { word: "able", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "table", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "cable", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "fable", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "stable", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "title", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "little", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "bottle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "battle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "cattle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "rattle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "settle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "nettle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "simple", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "ample", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "dimple", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "purple", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "turtle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "circle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "candle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "handle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "bundle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  // 4A consonant-le additions
  { word: "ankle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "apple", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "bubble", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "buckle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "chuckle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "cradle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "fiddle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "giggle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "gentle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "grumble", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "humble", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "jungle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "kettle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "marble", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "middle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "muddle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "needle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "nibble", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "paddle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "pickle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "puddle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "puzzle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "riddle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "ruffle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "sparkle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "stumble", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "tickle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "tumble", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "twinkle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "waffle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "wiggle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "wrinkle", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  // 4A dge (existing)
  { word: "badge", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  { word: "edge", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  { word: "ledge", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  { word: "hedge", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  { word: "wedge", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  { word: "bridge", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  { word: "fridge", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  { word: "judge", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  { word: "nudge", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  { word: "lodge", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  { word: "dodge", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  // 4A dge additions
  { word: "budge", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  { word: "ridge", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  { word: "smudge", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  { word: "grudge", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  { word: "pledge", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  { word: "sledge", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  { word: "dredge", isNonsense: false, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  // 4A nonsense
  { word: "zable", isNonsense: true, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "fudge", isNonsense: true, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  { word: "vattle", isNonsense: true, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "blidge", isNonsense: true, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },
  { word: "fumple", isNonsense: true, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "vingle", isNonsense: true, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "zabble", isNonsense: true, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "consonant-le", phonicPattern: "consonant-le" },
  { word: "drodge", isNonsense: true, level: "4A", levelNumber: 4, coinValue: 18, phonicFamily: "dge", phonicPattern: "dge" },

  // 4B – ew, ei, eigh, ue, eu, ui, ey
  { word: "new", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ew", phonicPattern: "vowel-team-ew" },
  { word: "few", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ew", phonicPattern: "vowel-team-ew" },
  { word: "dew", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ew", phonicPattern: "vowel-team-ew" },
  { word: "drew", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ew", phonicPattern: "vowel-team-ew" },
  { word: "grew", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ew", phonicPattern: "vowel-team-ew" },
  { word: "blew", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ew", phonicPattern: "vowel-team-ew" },
  { word: "veil", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ei", phonicPattern: "vowel-team-ei" },
  { word: "rein", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ei", phonicPattern: "vowel-team-ei" },
  { word: "eight", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "eigh", phonicPattern: "vowel-team-ei" },
  { word: "weigh", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "eigh", phonicPattern: "vowel-team-ei" },
  { word: "freight", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "eigh", phonicPattern: "vowel-team-ei" },
  { word: "blue", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ue", phonicPattern: "vowel-team-ew" },
  { word: "clue", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ue", phonicPattern: "vowel-team-ew" },
  { word: "glue", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ue", phonicPattern: "vowel-team-ew" },
  { word: "true", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ue", phonicPattern: "vowel-team-ew" },
  { word: "fruit", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ui", phonicPattern: "vowel-team-ew" },
  { word: "suit", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ui", phonicPattern: "vowel-team-ew" },
  { word: "juice", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ui", phonicPattern: "vowel-team-ew" },
  { word: "key", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ey", phonicPattern: "vowel-team-ew" },
  { word: "honey", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ey", phonicPattern: "vowel-team-ew" },
  { word: "money", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ey", phonicPattern: "vowel-team-ew" },
  { word: "turkey", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ey", phonicPattern: "vowel-team-ew" },
  // 4B ew additions
  { word: "chew", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ew", phonicPattern: "vowel-team-ew" },
  { word: "crew", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ew", phonicPattern: "vowel-team-ew" },
  { word: "flew", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ew", phonicPattern: "vowel-team-ew" },
  { word: "jewel", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ew", phonicPattern: "vowel-team-ew" },
  { word: "knew", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ew", phonicPattern: "vowel-team-ew" },
  { word: "screw", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ew", phonicPattern: "vowel-team-ew" },
  { word: "stew", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ew", phonicPattern: "vowel-team-ew" },
  { word: "threw", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ew", phonicPattern: "vowel-team-ew" },
  // 4B ei/eigh additions
  { word: "ceiling", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ei", phonicPattern: "vowel-team-ei" },
  { word: "receive", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ei", phonicPattern: "vowel-team-ei" },
  { word: "height", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "eigh", phonicPattern: "vowel-team-ei" },
  { word: "neighbor", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "eigh", phonicPattern: "vowel-team-ei" },
  { word: "sleigh", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "eigh", phonicPattern: "vowel-team-ei" },
  { word: "weight", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "eigh", phonicPattern: "vowel-team-ei" },
  // 4B ue additions
  { word: "argue", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ue", phonicPattern: "vowel-team-ew" },
  { word: "due", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ue", phonicPattern: "vowel-team-ew" },
  { word: "hue", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ue", phonicPattern: "vowel-team-ew" },
  { word: "rescue", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ue", phonicPattern: "vowel-team-ew" },
  { word: "value", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ue", phonicPattern: "vowel-team-ew" },
  // 4B ui additions
  { word: "bruise", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ui", phonicPattern: "vowel-team-ew" },
  { word: "build", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ui", phonicPattern: "vowel-team-ew" },
  { word: "built", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ui", phonicPattern: "vowel-team-ew" },
  { word: "cruise", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ui", phonicPattern: "vowel-team-ew" },
  { word: "guitar", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ui", phonicPattern: "vowel-team-ew" },
  // 4B ey additions
  { word: "alley", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ey", phonicPattern: "vowel-team-ew" },
  { word: "barley", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ey", phonicPattern: "vowel-team-ew" },
  { word: "chimney", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ey", phonicPattern: "vowel-team-ew" },
  { word: "donkey", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ey", phonicPattern: "vowel-team-ew" },
  { word: "hockey", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ey", phonicPattern: "vowel-team-ew" },
  { word: "jockey", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ey", phonicPattern: "vowel-team-ew" },
  { word: "monkey", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ey", phonicPattern: "vowel-team-ew" },
  { word: "pulley", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ey", phonicPattern: "vowel-team-ew" },
  { word: "trolley", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ey", phonicPattern: "vowel-team-ew" },
  { word: "valley", isNonsense: false, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ey", phonicPattern: "vowel-team-ew" },
  // 4B nonsense
  { word: "zew", isNonsense: true, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ew", phonicPattern: "vowel-team-ew" },
  { word: "veit", isNonsense: true, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ei", phonicPattern: "vowel-team-ei" },
  { word: "bluit", isNonsense: true, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ui", phonicPattern: "vowel-team-ew" },
  { word: "frue", isNonsense: true, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ue", phonicPattern: "vowel-team-ew" },
  { word: "zey", isNonsense: true, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ey", phonicPattern: "vowel-team-ew" },
  { word: "bleid", isNonsense: true, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ei", phonicPattern: "vowel-team-ei" },
  { word: "truice", isNonsense: true, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ui", phonicPattern: "vowel-team-ew" },
  { word: "foney", isNonsense: true, level: "4B", levelNumber: 4, coinValue: 18, phonicFamily: "ey", phonicPattern: "vowel-team-ew" },

  // 4C – prefixes un-/re-/dis-/pre-/con-, suffix+silent-e rule, suffix+y rule
  { word: "undo", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-un", phonicPattern: "prefix" },
  { word: "unhappy", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-un", phonicPattern: "prefix" },
  { word: "unlock", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-un", phonicPattern: "prefix" },
  { word: "unpack", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-un", phonicPattern: "prefix" },
  { word: "redo", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-re", phonicPattern: "prefix" },
  { word: "refill", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-re", phonicPattern: "prefix" },
  { word: "replay", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-re", phonicPattern: "prefix" },
  { word: "rerun", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-re", phonicPattern: "prefix" },
  { word: "dislike", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-dis", phonicPattern: "prefix" },
  { word: "disagree", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-dis", phonicPattern: "prefix" },
  { word: "disconnect", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-dis", phonicPattern: "prefix" },
  { word: "preview", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-pre", phonicPattern: "prefix" },
  { word: "prepay", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-pre", phonicPattern: "prefix" },
  { word: "preheat", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-pre", phonicPattern: "prefix" },
  { word: "connect", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-con", phonicPattern: "prefix" },
  { word: "contain", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-con", phonicPattern: "prefix" },
  { word: "contest", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-con", phonicPattern: "prefix" },
  { word: "hopeful", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  { word: "careful", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  { word: "useful", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  { word: "lovely", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  { word: "lately", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  { word: "closely", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  // 4C prefix-un additions
  { word: "unable", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-un", phonicPattern: "prefix" },
  { word: "unfair", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-un", phonicPattern: "prefix" },
  { word: "unfold", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-un", phonicPattern: "prefix" },
  { word: "unkind", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-un", phonicPattern: "prefix" },
  { word: "unknown", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-un", phonicPattern: "prefix" },
  { word: "unsafe", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-un", phonicPattern: "prefix" },
  { word: "untie", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-un", phonicPattern: "prefix" },
  // 4C prefix-re additions
  { word: "recall", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-re", phonicPattern: "prefix" },
  { word: "refresh", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-re", phonicPattern: "prefix" },
  { word: "remind", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-re", phonicPattern: "prefix" },
  { word: "remove", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-re", phonicPattern: "prefix" },
  { word: "repeat", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-re", phonicPattern: "prefix" },
  { word: "return", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-re", phonicPattern: "prefix" },
  { word: "rewind", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-re", phonicPattern: "prefix" },
  // 4C prefix-dis additions
  { word: "discard", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-dis", phonicPattern: "prefix" },
  { word: "discover", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-dis", phonicPattern: "prefix" },
  { word: "display", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-dis", phonicPattern: "prefix" },
  { word: "displace", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-dis", phonicPattern: "prefix" },
  // 4C prefix-pre additions
  { word: "predict", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-pre", phonicPattern: "prefix" },
  { word: "prepare", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-pre", phonicPattern: "prefix" },
  { word: "pretend", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-pre", phonicPattern: "prefix" },
  { word: "prevent", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-pre", phonicPattern: "prefix" },
  // 4C prefix-con additions
  { word: "conclude", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-con", phonicPattern: "prefix" },
  { word: "confirm", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-con", phonicPattern: "prefix" },
  { word: "confuse", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-con", phonicPattern: "prefix" },
  { word: "control", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-con", phonicPattern: "prefix" },
  // 4C suffix additions
  { word: "careless", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  { word: "fearless", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  { word: "helpless", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  { word: "thankful", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  { word: "cheerful", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  { word: "playful", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  { word: "graceful", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  { word: "painful", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  { word: "safely", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  { word: "nicely", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  { word: "brightly", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  { word: "kindness", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  { word: "darkness", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  { word: "sadness", isNonsense: false, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "suffix-rule", phonicPattern: "suffix-rule" },
  // 4C nonsense
  { word: "unpog", isNonsense: true, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-un", phonicPattern: "prefix" },
  { word: "reblit", isNonsense: true, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-re", phonicPattern: "prefix" },
  { word: "disflam", isNonsense: true, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-dis", phonicPattern: "prefix" },
  { word: "prestamp", isNonsense: true, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-pre", phonicPattern: "prefix" },
  { word: "conbelt", isNonsense: true, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-con", phonicPattern: "prefix" },
  { word: "unplox", isNonsense: true, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-un", phonicPattern: "prefix" },
  { word: "disframp", isNonsense: true, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-dis", phonicPattern: "prefix" },
  { word: "constak", isNonsense: true, level: "4C", levelNumber: 4, coinValue: 18, phonicFamily: "prefix-con", phonicPattern: "prefix" },
];
