export interface WordEntry {
  word: string;
  isNonsense: boolean;
  level: string;
  levelNumber: number;
  coinValue: number;
  phonicFamily: string;
  phonicPattern: string;
}

export const LEVEL2_WORDS: WordEntry[] = [
  // 2A – vowel teams ai, ay
  { word: "rain", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "main", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "pain", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "gain", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "tail", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "mail", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "sail", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "rail", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "wait", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "bait", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "day", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "say", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "may", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "way", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "ray", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "pay", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "play", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "stay", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "gray", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "spray", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  // 2A nonsense
  { word: "daim", isNonsense: true, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "vaip", isNonsense: true, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "zay", isNonsense: true, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "fay", isNonsense: true, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "waid", isNonsense: true, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  // 2A additional words
  { word: "chain", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "claim", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "drain", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "grain", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "plain", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "snail", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "trail", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "train", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "wail", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "maid", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "paid", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "raid", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "clay", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "slay", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "sway", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "tray", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "stray", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "fray", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "jay", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "lay", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "hay", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "bay", isNonsense: false, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },
  { word: "zaim", isNonsense: true, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "baid", isNonsense: true, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "glaim", isNonsense: true, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ai", phonicPattern: "vowel-team-ai" },
  { word: "yaip", isNonsense: true, level: "2A", levelNumber: 2, coinValue: 8, phonicFamily: "ay", phonicPattern: "vowel-team-ay" },

  // 2B – vowel teams ee, ea (long-e)
  { word: "see", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "bee", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "feet", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "meet", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "need", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "seed", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "week", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "feel", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "heel", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "peel", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "eat", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "beat", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "heat", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "meat", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "seat", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "leaf", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "read", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "bead", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "team", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "dream", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  // 2B nonsense
  { word: "teef", isNonsense: true, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "zeek", isNonsense: true, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "veat", isNonsense: true, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "feab", isNonsense: true, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "deem", isNonsense: true, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  // 2B additional words
  { word: "deep", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "free", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "green", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "keep", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "peek", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "sleep", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "steep", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "sweet", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "teen", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "three", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "tree", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "cheek", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "creek", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "reef", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "seek", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "beach", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "bean", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "cheap", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "clean", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "deal", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "feast", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "heal", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "lean", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "meal", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "peach", isNonsense: false, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "zeef", isNonsense: true, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "beel", isNonsense: true, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },
  { word: "feam", isNonsense: true, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ea", phonicPattern: "vowel-team-ea" },
  { word: "dreet", isNonsense: true, level: "2B", levelNumber: 2, coinValue: 8, phonicFamily: "ee", phonicPattern: "vowel-team-ee" },

  // 2C – r-controlled ar, or + open syllables (he, me, go)
  { word: "car", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "far", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "jar", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "bar", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "star", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "cart", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "farm", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "harm", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "park", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "dark", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "for", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "nor", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "corn", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "born", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "horn", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "torn", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "fort", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "sort", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "port", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "he", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "open-syl", phonicPattern: "open-syl" },
  { word: "me", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "open-syl", phonicPattern: "open-syl" },
  { word: "we", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "open-syl", phonicPattern: "open-syl" },
  { word: "go", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "open-syl", phonicPattern: "open-syl" },
  { word: "no", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "open-syl", phonicPattern: "open-syl" },
  { word: "so", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "open-syl", phonicPattern: "open-syl" },
  // 2C nonsense
  { word: "zar", isNonsense: true, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "forp", isNonsense: true, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "darm", isNonsense: true, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "vork", isNonsense: true, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  // 2C additional words
  { word: "arc", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "bark", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "barn", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "card", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "charm", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "dart", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "hard", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "harp", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "mark", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "scar", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "spark", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "tar", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "yarn", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "cord", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "ford", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "more", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "porch", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "score", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "shore", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "short", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "word", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "work", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "worm", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "worth", isNonsense: false, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "zarm", isNonsense: true, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "forb", isNonsense: true, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },
  { word: "barg", isNonsense: true, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "ar", phonicPattern: "r-ctrl-ar" },
  { word: "vorx", isNonsense: true, level: "2C", levelNumber: 2, coinValue: 8, phonicFamily: "or", phonicPattern: "r-ctrl-or" },

  // 2D – r-controlled er, ir, ur
  { word: "her", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "er", phonicPattern: "r-ctrl-er" },
  { word: "fern", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "er", phonicPattern: "r-ctrl-er" },
  { word: "herd", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "er", phonicPattern: "r-ctrl-er" },
  { word: "verb", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "er", phonicPattern: "r-ctrl-er" },
  { word: "bird", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ir", phonicPattern: "r-ctrl-ir" },
  { word: "dirt", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ir", phonicPattern: "r-ctrl-ir" },
  { word: "firm", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ir", phonicPattern: "r-ctrl-ir" },
  { word: "girl", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ir", phonicPattern: "r-ctrl-ir" },
  { word: "stir", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ir", phonicPattern: "r-ctrl-ir" },
  { word: "fur", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  { word: "burn", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  { word: "curl", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  { word: "hurt", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  { word: "turn", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  { word: "purse", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  { word: "nurse", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  // 2D nonsense
  { word: "ferp", isNonsense: true, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "er", phonicPattern: "r-ctrl-er" },
  { word: "zird", isNonsense: true, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ir", phonicPattern: "r-ctrl-ir" },
  { word: "vurn", isNonsense: true, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  { word: "wirt", isNonsense: true, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ir", phonicPattern: "r-ctrl-ir" },
  // 2D additional words
  { word: "per", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "er", phonicPattern: "r-ctrl-er" },
  { word: "perk", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "er", phonicPattern: "r-ctrl-er" },
  { word: "clerk", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "er", phonicPattern: "r-ctrl-er" },
  { word: "jerk", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "er", phonicPattern: "r-ctrl-er" },
  { word: "term", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "er", phonicPattern: "r-ctrl-er" },
  { word: "serve", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "er", phonicPattern: "r-ctrl-er" },
  { word: "stern", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "er", phonicPattern: "r-ctrl-er" },
  { word: "perch", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "er", phonicPattern: "r-ctrl-er" },
  { word: "chirp", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ir", phonicPattern: "r-ctrl-ir" },
  { word: "first", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ir", phonicPattern: "r-ctrl-ir" },
  { word: "shirt", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ir", phonicPattern: "r-ctrl-ir" },
  { word: "sir", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ir", phonicPattern: "r-ctrl-ir" },
  { word: "skirt", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ir", phonicPattern: "r-ctrl-ir" },
  { word: "swirl", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ir", phonicPattern: "r-ctrl-ir" },
  { word: "third", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ir", phonicPattern: "r-ctrl-ir" },
  { word: "birth", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ir", phonicPattern: "r-ctrl-ir" },
  { word: "burst", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  { word: "church", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  { word: "curb", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  { word: "curse", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  { word: "hurl", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  { word: "spur", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  { word: "surf", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  { word: "turf", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  { word: "urge", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  { word: "burp", isNonsense: false, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  { word: "zerm", isNonsense: true, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "er", phonicPattern: "r-ctrl-er" },
  { word: "firb", isNonsense: true, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ir", phonicPattern: "r-ctrl-ir" },
  { word: "vurt", isNonsense: true, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ur", phonicPattern: "r-ctrl-ur" },
  { word: "wirp", isNonsense: true, level: "2D", levelNumber: 2, coinValue: 8, phonicFamily: "ir", phonicPattern: "r-ctrl-ir" },

  // 2E – vowel teams oa, oe, ow (long-o)
  { word: "boat", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "coat", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "goat", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "load", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "road", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "soap", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "toad", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "toe", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oe", phonicPattern: "vowel-team-oa" },
  { word: "foe", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oe", phonicPattern: "vowel-team-oa" },
  { word: "hoe", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oe", phonicPattern: "vowel-team-oa" },
  { word: "row", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "low", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "show", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "slow", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "flow", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "snow", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "glow", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  // 2E nonsense
  { word: "doan", isNonsense: true, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "voe", isNonsense: true, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oe", phonicPattern: "vowel-team-oa" },
  { word: "zow", isNonsense: true, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "loab", isNonsense: true, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  // 2E additional words
  { word: "boast", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "cloak", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "float", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "foam", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "groan", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "moan", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "oat", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "roam", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "roast", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "soak", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "toast", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "doe", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oe", phonicPattern: "vowel-team-oa" },
  { word: "woe", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oe", phonicPattern: "vowel-team-oa" },
  { word: "bow", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "blow", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "grow", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "mow", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "own", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "throw", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "stow", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "crow", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "below", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "arrow", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "elbow", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "narrow", isNonsense: false, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "zoat", isNonsense: true, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "fow", isNonsense: true, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "ow-long", phonicPattern: "vowel-team-ow-long" },
  { word: "voan", isNonsense: true, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },
  { word: "loak", isNonsense: true, level: "2E", levelNumber: 2, coinValue: 8, phonicFamily: "oa", phonicPattern: "vowel-team-oa" },

  // 2F – oo (food), oo (book), ou, ow (diphthong)
  { word: "moon", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },
  { word: "food", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },
  { word: "cool", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },
  { word: "pool", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },
  { word: "tool", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },
  { word: "zoom", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },
  { word: "book", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-short", phonicPattern: "vowel-team-oo" },
  { word: "cook", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-short", phonicPattern: "vowel-team-oo" },
  { word: "hook", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-short", phonicPattern: "vowel-team-oo" },
  { word: "look", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-short", phonicPattern: "vowel-team-oo" },
  { word: "foot", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-short", phonicPattern: "vowel-team-oo" },
  { word: "good", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-short", phonicPattern: "vowel-team-oo" },
  { word: "wood", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-short", phonicPattern: "vowel-team-oo" },
  { word: "out", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ou", phonicPattern: "diphthong-ou" },
  { word: "shout", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ou", phonicPattern: "diphthong-ou" },
  { word: "cloud", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ou", phonicPattern: "diphthong-ou" },
  { word: "proud", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ou", phonicPattern: "diphthong-ou" },
  { word: "found", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ou", phonicPattern: "diphthong-ou" },
  { word: "ground", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ou", phonicPattern: "diphthong-ou" },
  { word: "cow", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ow-diph", phonicPattern: "diphthong-ow" },
  { word: "how", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ow-diph", phonicPattern: "diphthong-ow" },
  { word: "now", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ow-diph", phonicPattern: "diphthong-ow" },
  { word: "town", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ow-diph", phonicPattern: "diphthong-ow" },
  { word: "down", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ow-diph", phonicPattern: "diphthong-ow" },
  { word: "brown", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ow-diph", phonicPattern: "diphthong-ow" },
  // 2F nonsense
  { word: "foom", isNonsense: true, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },
  { word: "zook", isNonsense: true, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-short", phonicPattern: "vowel-team-oo" },
  { word: "vound", isNonsense: true, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ou", phonicPattern: "diphthong-ou" },
  { word: "tow", isNonsense: true, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ow-diph", phonicPattern: "diphthong-ow" },
  // 2F additional words
  { word: "bloom", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },
  { word: "groom", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },
  { word: "noon", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },
  { word: "room", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },
  { word: "roof", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },
  { word: "shoot", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },
  { word: "soon", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },
  { word: "spoon", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },
  { word: "tooth", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },
  { word: "troop", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },
  { word: "nook", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-short", phonicPattern: "vowel-team-oo" },
  { word: "shook", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-short", phonicPattern: "vowel-team-oo" },
  { word: "stood", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-short", phonicPattern: "vowel-team-oo" },
  { word: "took", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-short", phonicPattern: "vowel-team-oo" },
  { word: "count", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ou", phonicPattern: "diphthong-ou" },
  { word: "loud", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ou", phonicPattern: "diphthong-ou" },
  { word: "mound", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ou", phonicPattern: "diphthong-ou" },
  { word: "mouth", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ou", phonicPattern: "diphthong-ou" },
  { word: "pound", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ou", phonicPattern: "diphthong-ou" },
  { word: "round", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ou", phonicPattern: "diphthong-ou" },
  { word: "sound", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ou", phonicPattern: "diphthong-ou" },
  { word: "south", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ou", phonicPattern: "diphthong-ou" },
  { word: "brow", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ow-diph", phonicPattern: "diphthong-ow" },
  { word: "crowd", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ow-diph", phonicPattern: "diphthong-ow" },
  { word: "growl", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ow-diph", phonicPattern: "diphthong-ow" },
  { word: "howl", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ow-diph", phonicPattern: "diphthong-ow" },
  { word: "owl", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ow-diph", phonicPattern: "diphthong-ow" },
  { word: "plow", isNonsense: false, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ow-diph", phonicPattern: "diphthong-ow" },
  { word: "foop", isNonsense: true, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },
  { word: "zoud", isNonsense: true, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ou", phonicPattern: "diphthong-ou" },
  { word: "bown", isNonsense: true, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "ow-diph", phonicPattern: "diphthong-ow" },
  { word: "ploof", isNonsense: true, level: "2F", levelNumber: 2, coinValue: 8, phonicFamily: "oo-long", phonicPattern: "vowel-team-oo" },

  // 2G – nasals -ang/-ing/-ong/-ung, -ank/-ink/-onk/-unk, -all, ck, tch
  { word: "bang", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ang", phonicPattern: "nasal-ng" },
  { word: "gang", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ang", phonicPattern: "nasal-ng" },
  { word: "rang", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ang", phonicPattern: "nasal-ng" },
  { word: "sang", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ang", phonicPattern: "nasal-ng" },
  { word: "ring", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ing", phonicPattern: "nasal-ng" },
  { word: "sing", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ing", phonicPattern: "nasal-ng" },
  { word: "king", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ing", phonicPattern: "nasal-ng" },
  { word: "wing", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ing", phonicPattern: "nasal-ng" },
  { word: "song", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ong", phonicPattern: "nasal-ng" },
  { word: "long", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ong", phonicPattern: "nasal-ng" },
  { word: "gong", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ong", phonicPattern: "nasal-ng" },
  { word: "lung", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ung", phonicPattern: "nasal-ng" },
  { word: "hung", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ung", phonicPattern: "nasal-ng" },
  { word: "rung", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ung", phonicPattern: "nasal-ng" },
  { word: "bank", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ank", phonicPattern: "nasal-nk" },
  { word: "rank", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ank", phonicPattern: "nasal-nk" },
  { word: "sank", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ank", phonicPattern: "nasal-nk" },
  { word: "tank", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ank", phonicPattern: "nasal-nk" },
  { word: "ink", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ink", phonicPattern: "nasal-nk" },
  { word: "link", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ink", phonicPattern: "nasal-nk" },
  { word: "pink", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ink", phonicPattern: "nasal-nk" },
  { word: "sink", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ink", phonicPattern: "nasal-nk" },
  { word: "bunk", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-unk", phonicPattern: "nasal-nk" },
  { word: "dunk", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-unk", phonicPattern: "nasal-nk" },
  { word: "junk", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-unk", phonicPattern: "nasal-nk" },
  { word: "all", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-all", phonicPattern: "word-family-all" },
  { word: "ball", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-all", phonicPattern: "word-family-all" },
  { word: "call", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-all", phonicPattern: "word-family-all" },
  { word: "fall", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-all", phonicPattern: "word-family-all" },
  { word: "hall", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-all", phonicPattern: "word-family-all" },
  { word: "tall", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-all", phonicPattern: "word-family-all" },
  { word: "back", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "ck", phonicPattern: "ck" },
  { word: "deck", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "ck", phonicPattern: "ck" },
  { word: "kick", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "ck", phonicPattern: "ck" },
  { word: "lock", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "ck", phonicPattern: "ck" },
  { word: "duck", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "ck", phonicPattern: "ck" },
  { word: "catch", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "tch", phonicPattern: "tch" },
  { word: "hatch", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "tch", phonicPattern: "tch" },
  { word: "match", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "tch", phonicPattern: "tch" },
  { word: "patch", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "tch", phonicPattern: "tch" },
  { word: "fetch", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "tch", phonicPattern: "tch" },
  { word: "witch", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "tch", phonicPattern: "tch" },
  { word: "hutch", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "tch", phonicPattern: "tch" },
  // 2G nonsense
  { word: "fang", isNonsense: true, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ang", phonicPattern: "nasal-ng" },
  { word: "vink", isNonsense: true, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ink", phonicPattern: "nasal-nk" },
  { word: "zunk", isNonsense: true, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-unk", phonicPattern: "nasal-nk" },
  { word: "dall", isNonsense: true, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-all", phonicPattern: "word-family-all" },
  { word: "veck", isNonsense: true, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "ck", phonicPattern: "ck" },
  { word: "zatch", isNonsense: true, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "tch", phonicPattern: "tch" },
  // 2G additional words
  { word: "clang", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ang", phonicPattern: "nasal-ng" },
  { word: "flung", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ung", phonicPattern: "nasal-ng" },
  { word: "sling", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ing", phonicPattern: "nasal-ng" },
  { word: "sting", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ing", phonicPattern: "nasal-ng" },
  { word: "drank", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ank", phonicPattern: "nasal-nk" },
  { word: "plank", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ank", phonicPattern: "nasal-nk" },
  { word: "skunk", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-unk", phonicPattern: "nasal-nk" },
  { word: "trunk", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-unk", phonicPattern: "nasal-nk" },
  { word: "yank", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-ank", phonicPattern: "nasal-nk" },
  { word: "wall", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-all", phonicPattern: "word-family-all" },
  { word: "small", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-all", phonicPattern: "word-family-all" },
  { word: "stall", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "-all", phonicPattern: "word-family-all" },
  { word: "lick", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "ck", phonicPattern: "ck" },
  { word: "sock", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "ck", phonicPattern: "ck" },
  { word: "itch", isNonsense: false, level: "2G", levelNumber: 2, coinValue: 8, phonicFamily: "tch", phonicPattern: "tch" },

  // 2H – -ed endings, qu, y-as-vowel (long-i / long-e)
  { word: "jumped", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /t/", phonicPattern: "ed-ending" },
  { word: "walked", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /t/", phonicPattern: "ed-ending" },
  { word: "clapped", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /t/", phonicPattern: "ed-ending" },
  { word: "played", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /d/", phonicPattern: "ed-ending" },
  { word: "rained", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /d/", phonicPattern: "ed-ending" },
  { word: "filled", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /d/", phonicPattern: "ed-ending" },
  { word: "wanted", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /id/", phonicPattern: "ed-ending" },
  { word: "landed", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /id/", phonicPattern: "ed-ending" },
  { word: "handed", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /id/", phonicPattern: "ed-ending" },
  { word: "quit", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "qu", phonicPattern: "qu" },
  { word: "quiz", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "qu", phonicPattern: "qu" },
  { word: "quick", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "qu", phonicPattern: "qu" },
  { word: "quill", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "qu", phonicPattern: "qu" },
  { word: "queen", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "qu", phonicPattern: "qu" },
  { word: "quest", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "qu", phonicPattern: "qu" },
  { word: "my", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  { word: "by", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  { word: "fly", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  { word: "cry", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  { word: "dry", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  { word: "try", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  { word: "funny", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  { word: "happy", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  { word: "puppy", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  { word: "baby", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  // 2H nonsense
  { word: "queb", isNonsense: true, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "qu", phonicPattern: "qu" },
  { word: "zipped", isNonsense: true, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed", phonicPattern: "ed-ending" },
  { word: "fappy", isNonsense: true, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  { word: "vly", isNonsense: true, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  // 2H additional words
  { word: "asked", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /t/", phonicPattern: "ed-ending" },
  { word: "baked", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /t/", phonicPattern: "ed-ending" },
  { word: "fixed", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /t/", phonicPattern: "ed-ending" },
  { word: "grabbed", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /d/", phonicPattern: "ed-ending" },
  { word: "kicked", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /t/", phonicPattern: "ed-ending" },
  { word: "liked", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /t/", phonicPattern: "ed-ending" },
  { word: "locked", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /t/", phonicPattern: "ed-ending" },
  { word: "pushed", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /t/", phonicPattern: "ed-ending" },
  { word: "reached", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /t/", phonicPattern: "ed-ending" },
  { word: "raced", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /t/", phonicPattern: "ed-ending" },
  { word: "saved", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /d/", phonicPattern: "ed-ending" },
  { word: "watched", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /t/", phonicPattern: "ed-ending" },
  { word: "worked", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed /t/", phonicPattern: "ed-ending" },
  { word: "quarrel", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "qu", phonicPattern: "qu" },
  { word: "quart", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "qu", phonicPattern: "qu" },
  { word: "any", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  { word: "body", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  { word: "bunny", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  { word: "candy", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  { word: "carry", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  { word: "easy", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  { word: "fifty", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  { word: "cozy", isNonsense: false, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
  { word: "zumped", isNonsense: true, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed", phonicPattern: "ed-ending" },
  { word: "bipped", isNonsense: true, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "-ed", phonicPattern: "ed-ending" },
  { word: "vunny", isNonsense: true, level: "2H", levelNumber: 2, coinValue: 8, phonicFamily: "y-vowel", phonicPattern: "y-vowel" },
];
