import type { Metadata } from "next";
import LegalPage from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy — Roll & Read",
  description: "How Roll & Read collects, uses, and protects information for parents, teachers, and children.",
};

const SUPPORT_EMAIL = "support@rollandreadgame.com";

export default function PrivacyPolicyPage() {
  return (
    <LegalPage title="Privacy Policy" lastUpdated="June 11, 2026">
      <p>
        Roll &amp; Read (&ldquo;Roll &amp; Read,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or
        &ldquo;our&rdquo;) provides a phonics-based reading game for children, set up and managed by
        parents, guardians, and teachers. This Privacy Policy explains what information we collect,
        how we use it, and the choices available to you. We designed Roll &amp; Read to be
        child-friendly and privacy-respecting: <strong>accounts are created and controlled by
        adults</strong>, and children only play the game.
      </p>

      <h2>1. Who creates and controls accounts</h2>
      <p>
        Roll &amp; Read accounts may only be created by an adult who is the parent or legal guardian
        of a child, or a teacher acting in an educational capacity. The adult account holder creates
        and manages one or more child &ldquo;reader profiles.&rdquo; Children do not create accounts,
        enter payment information, or sign up themselves.
      </p>

      <h2>2. Information we collect</h2>
      <h3>From the adult account holder</h3>
      <ul>
        <li><strong>Account information</strong> — your email address and authentication details, handled by our authentication provider (Clerk).</li>
        <li><strong>Payment information</strong> — if you subscribe, billing is processed by Stripe. We do <strong>not</strong> store your full card number; we keep only a Stripe customer reference and your subscription status and plan.</li>
      </ul>
      <h3>About child reader profiles</h3>
      <ul>
        <li><strong>Profile details you enter</strong> — a first name (or nickname) and an avatar emoji you choose for each child.</li>
        <li><strong>Gameplay data</strong> — reading level, coins earned, stickers collected, accuracy, words practiced, session history, and streaks. This is used to run the game and show progress.</li>
      </ul>
      <h3>Automatically</h3>
      <ul>
        <li><strong>Basic technical data</strong> — standard server and security logs (such as IP address and device/browser type) generated by our hosting and infrastructure providers to operate and protect the service.</li>
      </ul>
      <p>We do <strong>not</strong> use advertising, we do <strong>not</strong> sell or rent personal information, and we do <strong>not</strong> use third-party advertising trackers.</p>

      <h2>3. Children&rsquo;s privacy (COPPA)</h2>
      <p>
        Roll &amp; Read is intended to be operated by adults on behalf of children. We do not knowingly
        collect personal information directly from children. The limited information associated with a
        child profile (a first name/nickname, an avatar, and gameplay progress) is entered and
        controlled by the adult account holder, who provides consent on the child&rsquo;s behalf when
        creating the profile.
      </p>
      <p>
        For classroom use, teachers may provide consent on behalf of parents for the use of the
        service for educational purposes, consistent with the COPPA &ldquo;school&rdquo; exception.
        Schools and teachers are responsible for complying with their own notice and consent
        obligations to parents.
      </p>
      <p>
        Parents, guardians, and teachers can review, edit, and delete a child&rsquo;s profile and its
        associated data at any time from the app&rsquo;s settings. Deleting a profile removes its
        gameplay data, word bank, stickers, and session history.
      </p>

      <h2>4. How we use information</h2>
      <ul>
        <li>To provide and operate the game and save progress.</li>
        <li>To create and manage your account and subscription.</li>
        <li>To provide customer support and respond to your requests.</li>
        <li>To keep the service secure and prevent abuse.</li>
        <li>To comply with legal obligations.</li>
      </ul>

      <h2>5. Service providers we use</h2>
      <p>We share information only with vendors who help us run the service, under agreements that limit their use of the data:</p>
      <ul>
        <li><strong>Clerk</strong> — account authentication.</li>
        <li><strong>Convex</strong> — application database and backend.</li>
        <li><strong>Stripe</strong> — subscription payments.</li>
        <li><strong>Vercel</strong> — website hosting.</li>
        <li><strong>Cloudflare</strong> — sticker image delivery (CDN).</li>
      </ul>

      <h2>6. Data retention and deletion</h2>
      <p>
        We keep account and profile data for as long as your account is active. You can delete
        individual child profiles in the app, and you can request deletion of your entire account and
        associated data by contacting us at <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.
        We will delete or anonymize data when it is no longer needed, except where we must retain it to
        meet legal or accounting obligations.
      </p>

      <h2>7. Security</h2>
      <p>
        We use reputable providers and reasonable technical and organizational measures to protect
        information. No method of transmission or storage is perfectly secure, but we work to protect
        your information and to limit access to it.
      </p>

      <h2>8. Your choices and rights</h2>
      <p>
        Depending on where you live, you may have rights to access, correct, or delete personal
        information, or to object to certain processing. To exercise these rights, contact us at{" "}
        <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. Because accounts are adult-managed, we
        respond to such requests through the adult account holder.
      </p>

      <h2>9. Changes to this policy</h2>
      <p>
        We may update this Privacy Policy from time to time. If we make material changes, we will
        update the &ldquo;Last updated&rdquo; date and, where appropriate, notify you.
      </p>

      <h2>10. Contact us</h2>
      <p>
        Questions about this Privacy Policy or your data? Email us at{" "}
        <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.
      </p>
    </LegalPage>
  );
}
